# when code is pushed to main, trigger the CI
name: CI

on:
  push:
    branches:
      - main


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

        #https://github.com/JamesIves/github-pages-deploy-action/tree/v4.3.3/
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.3.0
              with: 
                branch: main
                folder: docs
        