name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      run: |
        git checkout -b gh-pages  # 切换到 GitHub Pages 分支
        git add index.html  # 添加您的静态文件
        git commit -m "Auto-deploy via GitHub Actions"
        git push --force origin gh-pages  # 强制推送到 GitHub Pages 分支
