name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Git user identity
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Check if gh-pages branch exists
      run: |
        if [ ! `git branch --list gh-pages` ]; then
          git checkout --orphan gh-pages
        else
          git checkout gh-pages
        fi

    # - name: Hello world action
    #   with: # Set the secret as an input
    #    super_secret: ${{ secrets.SuperSecret }}
    #   env: # Or as an environment variable
    #     super_secret: ${{ secrets.SuperSecret }}

    - name: Deploy to GitHub Pages
      run: |
        git add .
        git commit -m "Auto-deploy via GitHub Actions"
        git push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/zGravityForce/html_test.git" gh-pages

    # env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}